{
	"version": 1514334851,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite3-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite4-sheet2.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/tiledbackground7.png",
		"images/tiledbackground8.png",
		"images/sprite2-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/tiledbackground9.png",
		"images/sprite6-sheet0.png",
		"images/vida-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/tiledbackground10.png",
		"images/tiledbackground12.png",
		"images/tiledbackground13.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/moedafixa-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/inimigo-sheet0.png",
		"images/inimigo-sheet1.png",
		"images/bala-sheet0.png",
		"images/cubodeguerra-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/tiledbackground16.png",
		"images/tiledbackground17.png",
		"images/tiledbackground18.png",
		"images/cubodeguerra2-sheet0.png",
		"images/tiledbackground19.png",
		"images/tiledbackground20.png",
		"images/goomba-sheet0.png",
		"images/goomba-sheet1.png",
		"images/goomba-sheet2.png",
		"images/barreira-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite17-sheet1.png",
		"media/cicle life-mc-(2)- (online-audio-converter.com).m4a",
		"media/cicle life-mc-(2)- (online-audio-converter.com).ogg",
		"media/fail som.m4a",
		"media/fail som.ogg",
		"media/palmas som.m4a",
		"media/palmas som.ogg",
		"media/dano.m4a",
		"media/dano.ogg",
		"media/scorpions (online-audio-converter.com).m4a",
		"media/scorpions (online-audio-converter.com).ogg",
		"media/last (online-audio-converter.com).m4a",
		"media/last (online-audio-converter.com).ogg",
		"media/mario_moeda_efeito_sonoro_toquesengracadosmp3.com (online-audio-converter.com).m4a",
		"media/mario_moeda_efeito_sonoro_toquesengracadosmp3.com (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}